### ISSUE TITLE
Impact of new empty std::set include in Node.hpp on performance and computational overhead.

### ISSUE THREAD

**Issue by BJackal** [Chaste/Chaste#105]
Auatay branch will introduce a new std::set<unsigned> mEdgeIndices to the Node class in mesh. Needs to be investigated how this will impact large scale simulations such as cardiac. As an empty set can take up to 40 bytes of memory which could introduce greater computational overheads on large scale simulations.

This will be investigated to asses exactly how the new set is used and how such overheads may be reduced. This may be along the line of having the set contained within a unique pointer. When set to a nullptr this could reduce the overhead to only 8 bytes per node.

**Comment by mirams** [comment]
Since `Node`s appear in lots of places that have no concept of an ‘edge’ it feels like the wrong place for this information to be stored? (Even a `NodeThatKeepsTrackOfWhatEdgesItIsIn` (!) subclass might be better if it is needed in some places. But if @jmpf is persuaded it’s the best option I will be onboard!

**Comment by jmpf** [comment]
@mirams: I do not want you to think that I am persuaded or that I endorse the changes.  **Quite the opposite.**  This issue/ticket is here because I am **not** persuaded that the code should be here.  

The fact is that the pull request has a deadline to it.  No-one fully-understands the design decisions made when this code was written and no-one has the time to write it better.  We need to decide 
- does it impact the cardiac code performance
- if so, should it be reverted
- if not reverted then can we redesign it in such a way that it doesn't impact memory footprint.

**Comment by BJackal** [comment]
After looking over the code it has been decided that this information does not need to be kept in the node Class and has been removed by @fcooper8472. So this should no longer be an issue for Node or the Cardiac portion of Chaste code. @jmpf @mirams

**Comment by AlexFletcher** [comment]
Does that mean this issue can be closed?

**Comment by BJackal** [comment]
Yes, I believe this issue can now be closed as we have merged the newer changes into develop and removed the empty set.
