### ISSUE TITLE
Post-workshop activities

### ISSUE THREAD

**Issue by AlexFletcher** [Chaste/Chaste#164]
- [x] @fcooper8472 to make Oxford workshop materials publicly accessible, via the "Doc" menu from https://chaste.github.io
- [x] @fcooper8472 to send out simple Google Form survey to workshop attendees asking what they thought went well, what could have gone better, what (if anything) they might use Chaste for in future, and what they'd like to see at future workshops
- [x] @fcooper8472 to process expenses claims and determine how much of the £10k remains for additional workshops/hackathons
- [x] ~@fcooper8472~ ~@MILeach~ ~@kwabenantim~ ~@jmpf~ ~@BJackal~ ~@mirams~ ~@AlexFletcher~ ~@bdevans~ to record their thoughts on how the workshop went and lessons learned for future workshops, as comments on this issue

**Comment by AlexFletcher** [comment]
My thoughts on the workshop and suggestions for future workshops:

- We don't need much time for lightning talks. More generally, we could probably have packed this workshop into 2 (or 2.5) days - there seemed to be quite a lot of gaps and breaks.
- I thought the case studies were good.
- We need to prepare our materials more in advance, and go through them all to check everything works as expected ahead of the workshop.
- We should advertise for longer, and more widely, and choose a time of year when we think attendees are most likely to make it (and when we aren't all already busy with annual leave, other workshops, or teaching prep for the new semester).
- It would be good to hold practicals in a room where all attendees can see a speaker and their screen/projector at the same time, e.g. if we want to go through a particular bit of code or installation instructions with the room.
- It might be a good idea to assign specific developers as demonstrators for specific practicals, to ensure we have good coverage in each session.
- We need to give attendees more warning about hardware requirements and what they need to install before the workshop, and possibly chase them up about this before the workshop.
- It would be good to have access to at least a few desktops or laptops with Chaste pre-installed, in case we again encounter attendees who simply aren't able to install and run Chaste on their own machine during the workshop (due to hardware limitations or their host institution's IT restrictions).
- We may wish to consider a narrower biological theme to the next workshop (e.g. "cancer", "developmental biology", or "physiology") to increase the chances of attracting attendees, particularly those with relevant research interests.
- We should think about what new functionality we'd like in place by the time of the next workshop, e.g. 3D vertex models.

**Comment by mirams** [comment]
I would like 3D vertex models!

**Comment by BJackal** [comment]
- I feel it would be better to advertise maybe 3+ months in advance to allow for a wider range of people to travel to the workshops.
- Similarly, it should be made clear to people in a similar time scale what software will be required for the event.
- Having 3-5 desktops with Chaste and pre-requisite software installed would be perfect to avoid the issues we had with users being unable to get software up and running. However, If we advertise that there will be some desktops it may be a a good idea to make it clear that pair programming mah be necessary if too many people require them.
- Materials should be finished off, shared and tested maybe a week+ before the event to avoid any issues.
- For the practicals having a room with a projector all participants can see would be useful so an example can be shown or any frequently asked question solutions could be demonstrated here.

**Comment by kwabenantim** [comment]
* We could prepare a Linux server (local or cloud) for participants to ssh into if all else fails.
* Given the number of participants using Windows, it might be a good idea to test everything on Windows before the workshop.
* The list of minimum hardware requirements we publicise should probably include free hard drive space.

**Comment by bdevans** [comment]
It's a point that has already been made several times, but I would also say that we should emphasise the need to have the required software pre-installed, security policies that allow it and hardware capable of running it. Without those issues resolved in advance, a lot of time gets wasted and a lot of frustration occurs. 

If we can ensure the above and iron out the new Windows instructions for working with Docker and WSL2, then the workshop should be relatively smooth.

Also, no gruel for breakfast 🤢

**Comment by fcooper8472** [comment]
I don't have anything to add to the existing feedback. I will investigate what options exist for giving people access to a Chaste-ready cloud VM in their web browser.

**Comment by jmpf** [comment]
Any constructive criticism I had has already been said.  I think that we weren't amazingly underprepared and that the docker solution looked robust enough to cover all eventualities.

- We should keep revisiting instructions and streamline/clarify as much as possible

**Comment by bdevans** [comment]
> I will investigate what options exist for giving people access to a Chaste-ready cloud VM in their web browser.

One option would be to provision a big server with ssh access for each user who needs it so that they can spin up their own docker container (from the same image) as required. They would just have to give each one a unique name (or omit the argument to get a random one) and we would need to ensure that dividing the resources by _n_ users would still leave enough for each container (RAM in particular which is statically allocated, CPUs are shared dynamically).

**Comment by MILeach** [comment]
- I agree with the above comments re: material preparation & hardware/software set up ahead of time.
- I think the workshop was a success overall. Practical sessions were a good length and contained about the right amount of content, sadly the sessions were dominated by installation issues for a significant number of people. Most people I spoke to felt that chaste was flexible and useful, and seemed to have a good understanding of its capabilities by the end of the workshop. 
- Python notebooks were very effective as an introductory tool - It could be a good idea to include one/some of these on the main chaste website so that people can have a go with chaste in their browser. A couple of people ran into minor issues with them and had to restart the notebook a few times; it would be worth investigating and fixing this.
- We should make sure we have uniform build instructions/project structure across the different workshop practicals. Having different structures/build processes didn't cause any major issues, but by unifying this participants could focus more on the chaste specifics rather than getting confused by alternate ways of using cmake etc.
- Some attendees expressed that it would have been nice to have time to go round the city a bit during the day. This obviously isn't directly workshop related, but perhaps reflects some would have liked a less packed schedule. One possibility would be to include a tour of the city or similar during the day as a networking/social event to break things up a bit.

**Comment by jmpf** [comment]
Kwabena (and Gary?) claiming through Nottingham.
Two other attendees yet to claim.

**Comment by mirams** [comment]
> Kwabena (and Gary?) claiming through Nottingham. Two other attendees yet to claim.

was going to ask what you wanted us to do there!
