### ISSUE TITLE
Migrate tutorials to new website

### ISSUE THREAD

**Issue by fcooper8472** [Chaste/Chaste#193]
This issue is to track any remaining problems with how tutorials are being displayed on the website:

https://chaste.github.io/docs/user-tutorials/

**Comment by AlexFletcher** [comment]
I've just had a look through the cell-based user tutorials and have spotted the following issues - some of these go beyond syntax but I thought I'd record them here while they were on my mind:

[Cell Based Demo](https://chaste.github.io/docs/user-tutorials/cellbaseddemo)
- [x] Broken link: "[wiki:UserTutorials/CreatingAndUsingANewCellProperty]"
- [x] Formatting: in "using the MAKE_PTR macro as follows", format "MAKE_PTR" as code
- [x] Broken link: "[wiki:UserTutorials/VisualizingWithParaview]"

[Creating And Using A New Cell Based Simulation Modifier](https://chaste.github.io/docs/user-tutorials/creatingandusinganewcellbasedsimulationmodifier)
- [x] Formatting: in "in the CellData property", format "CellData" as code

[Creating And Using A New Cell Cycle Model](https://chaste.github.io/docs/user-tutorials/creatingandusinganewcellcyclemodel)
- [x] Formatting: in "the Boost shared_ptr smart pointer", format "shared_ptr" as code
- [x] Formatting: in "the NEVER_REACHED macro", format "NEVER_REACHED" as code
- [x] Formatting: in "except for except for CheckReadyToDivideAndPhaseIsUpdated", for consistency should we add brackets to emphasise that CheckReadyToDivideAndPhaseIsUpdated is a function, as is done elsewhere?
- [x] Broken link: "ChasteGuides/BoostSerialization"
- [x] Formatting: in "the concrete class MyCellCycleModel", format "MyCellCycleModel" as code

[Creating And Using A New Cell Killer](https://chaste.github.io/docs/user-tutorials/creatingandusinganewcellkiller/)
- [x] Formatting: in "the equation (‘‘x’’/20)^2^ + (‘‘y’’/10)^2^ < 1", remove the " and extra ^
- [x] Broken link: "[wiki:UserTutorials/CreatingAndUsingANewCellCycleModel]"
- [x] Formatting/typo: in "the macro MAKR_PTR_ARGS", format "MAKR_PTR_ARGS" as code and fix the typo in it

[Creating And Using A New Cell Mutation State](https://chaste.github.io/docs/user-tutorials/creatingandusinganewcellmutationstate)
- [x] Formatting: in "Murphy et al, FASEB J. 14:2291-2302 (2000)", add a hyperlink to the DOI for this paper (https://doi.org/10.1096/fj.00-0128com)
- [x] Formatting: in "a serialize() method", format "serialize()" as code
- [x] Broken link: "ChasteGuides/BoostSerialization"

[Creating And Using A New Cell Population Boundary Condition](https://chaste.github.io/docs/user-tutorials/creatingandusinganewcellpopulationboundarycondition)
- [x] Formatting: in "0 <= y <= 5", is it possible to display the inequalities as mathematical symbols?
- [x] Broken link: "[wiki:UserTutorials/CreatingAndUsingANewCellKiller]"

[Creating And Using A New Cell Property](https://chaste.github.io/docs/user-tutorials/creatingandusinganewcellproperty)
- [x] Broken link: "[wiki:UserTutorials/CreatingAndUsingANewForce]"
- [x] Broken link: "[wiki:UserTutorials/CreatingAndUsingANewCellMutationState]"
- [x] Formatting: in "Owen ‘’et al.’’, J. Theor. Biol. 226: 377-391 (2004)", remove the extra " and add a hyperlink to the DOI for this paper (https://doi.org/10.1016/j.jtbi.2003.09.004)
- [x] Formatting: in "a serialize() method", format "serialize()" as code
- [x] Broken link: "[wiki:UserTutorials/CreatingAndUsingANewCellKiller]"
- [x] Broken link: "ChasteGuides/BoostSerialization"
- [x] Formatting: in "Note that HoneycombMeshGenerator", format "HoneycombMeshGenerator" as code
- [x] Formatting: in "T = t,,1,, + t,,2,,, where t,,1,, is a parameter representing the G,,1,, duration of a stem cell, and t,,2,, is the basic S+G,,2,,+M", sort out odd ,, and +

[Creating And Using A New Force](https://chaste.github.io/docs/user-tutorials/creatingandusinganewforce)
- [x] Formatting: in "a serialize method", format "serialize" as code and add brackets to emphasise it's a function
- [x] Formatting: in "the negative ‘‘y’’-direction", remove the "
- [x] Broken link: "[wiki:UserTutorials/CreatingAndUsingANewCellKiller]"
- [x] Formatting: in "This tests the CHASTE_CLASS_EXPORT(MyForce)", format "CHASTE_CLASS_EXPORT(MyForce)" as code

[Creating And Using A New Srn Model](https://chaste.github.io/docs/user-tutorials/creatingandusinganewsrnmodel)
- [x] Formatting: in "the Boost shared_ptr smart pointer", format "shared_ptr" as code
- [x] Formatting: in "the NEVER_REACHED macro", format "NEVER_REACHED" as code
- [x] Formatting: in "we solve a simple ODE dx/dt = -0.25*y dy/dt = x This has exact solution x = A cos 0.5t + B sin 0.5t", add some punctuation
- [x] Formatting: in "a serialize method", format "serialize" as code and add brackets to emphasise it's a function
- [x] Broken link: "ChasteGuides/BoostSerialization"
- [x] Formatting: in "Check that the ODE system is solved correctly", add a full stop
- [x] Formatting: in "the state of the ODES", replace "ODES" with "ODEs"
- [x] Formatting: in "using the macro MAKE_PTR", format "MAKE_PTR" as code
- [x] Formatting: in "the shared_ptr", format "shared_ptr" as code
- [x] Formatting: in "simple Stochastic cell cycle model", de-capitalise "Stochastic" and check if this ought to be changed to "UniformG1GenerationalCellCycleModel"
- [x] Broken link: "UserTutorials/VisualizingWithParaview"

[Creating And Using New Cell Based Writers](https://chaste.github.io/docs/user-tutorials/creatingandusingnewcellbasedwriters/)
- [x] Broken link: "[wiki:UserTutorials/CreatingAndUsingANewCellProperty]" (multiple occurrences)

(Didn't spot anything in [Running Contact Inhibition Simulations](https://chaste.github.io/docs/user-tutorials/runningcontactinhibitionsimulations))

[Running Crypt Simulations With Mutations](https://chaste.github.io/docs/user-tutorials/runningcryptsimulationswithmutations)
- [x] Formatting: in "the paper by Osborne ‘’et al.’’ (2010) [10.1098/rsta.2010.0173]", remove the extra " and add a hyperlink to the DOI for this paper
- [x] Formatting: in "These can be found in the inheritance diagram, here, AbstractCellMutationState", make it clearer that there's a hyperlink here
- [x] Formatting: in "(i.e. p_state)", format "p_state" as code

[Running Delta Notch Simulations](https://chaste.github.io/docs/user-tutorials/runningdeltanotchsimulations)
- [x] Formatting: in "Collier et al. (“Pattern formation by lateral inhibition with feedback: a mathematical model of delta-notch intercellular signalling”, J. Theor. Biol. 183:429-446)", add a hyperlink to this paper (https://doi.org/10.1006/jtbi.1996.0233)
- [x] Formatting: in "because Vertex simulations", de-capitalise "Vertex"
- [x] Broken link: "UserTutorials/VisualizingWithParaview"
- [x] Formatting: in "because HoneycombMeshGenerator", format "HoneycombMeshGenerator" as code

[Running Crypt Simulations With Mutations](https://chaste.github.io/docs/user-tutorials/runningcryptsimulationswithmutations)
- [x] Formatting: in "Osborne ‘’et al.’’ (2010) [10.1098/rsta.2010.0173]", remove the extra " and add a hyperlink to the DOI for this paper
- [x] Formatting: in "These can be found in the inheritance diagram, here, AbstractCellMutationState", make it clearer that there's a hyperlink here
- [x] Formatting: in "then call Solve()", format "Solve()" as code
- [x] Formatting: in "(i.e. p_state)", format "p_state" as code

[Running Differential Adhesion Simulations](https://chaste.github.io/docs/user-tutorials/runningdifferentialadhesionsimulations)
- [x] Broken link: "TestRunningPottsBasedSimulationsTutorial"
- [x] Broken link: "TestRunningVertexBasedSimulationsTutorial"
- [x] Broken link: "UserTutorials/VisualizingWithParaview"

[Running Mesh Based Crypt Simulations](https://chaste.github.io/docs/user-tutorials/runningmeshbasedcryptsimulations)
- [x] Formatting: in "van Leeuwen ‘’et al.’’ (2009) [doi:10.1111/j.1365-2184.2009.00627.x]", remove the extra " and add a hyperlink to the DOI for this paper
- [x] Broken link: "UserTutorials/RunningMeshBasedSimulations"
- [x] Formatting: in "(relative to “/tmp/<USER_NAME>/testoutput”)", format "/tmp/<USER_NAME>/testoutput" as code
- [x] Broken link: "ChasteGuides/RunningCellBasedVisualization"
- [x] Formatting: in "then call Solve()", format "Solve()" as code

[Running Node Based Simulations](https://chaste.github.io/docs/user-tutorials/runningnodebasedsimulations)
- [x] Formatting: in "Pathamathan et al “A computational study of discrete mechanical tissue models”, Physical Biology. Vol. 6. No. 3. 2009.. DOI (10.1088/1478-3975/6/3/036001)", add a hyperlink to the DOI for this paper
- [x] Broken link: "UserTutorials/RunningMeshBasedSimulations"
- [x] Formatting: in "we need to select the ‘Cells as circlesoption to be able to visualize the cells, as opposed to just the centres. We may have to do:javac Visualize2dCentreCells.java` beforehand", capitalise "we" and fix code formatting
- [x] Broken link: "UserTutorials/VisualizingWithParaview"
- [x] Formatting: in "These can be found in the inheritance diagram, here, AbstractCellPopulationBoundaryCondition", make it clearer that there's a hyperlink here
- [x] Formatting: in "using the MAKE_PTR_ARGS macro", format "MAKE_PTR_ARGS" as code

[Running Potts Based Simulations](https://chaste.github.io/docs/user-tutorials/runningpottsbasedsimulations)
- [x] Formatting: in "Graner, F. and Glazier, J. A. (1992). Simulation of biological cell sorting using a two-dimensional extended Potts model. Phys. Rev. Lett., 69(13):2015–2016", add a hyperlink to the DOI for this paper (https://doi.org/10.1103/PhysRevLett.69.2013)
- [x] Formatting: in "the Potts Simulation", de-capitalise "Simulation"
- [x] Broken link: "UserTutorials/VisualizingWithParaview"
- [x] Formatting: in "visualize in paraview", capitalise "paraview"

[Running Tumour Spheroid Simulations](https://chaste.github.io/docs/user-tutorials/runningtumourspheroidsimulations)
- [x] Formatting: in "we used a helper classes ((CellsGenerator", remove "a" and the extra opening bracket
- [x] Formatting: in "T = t,,1,, + t,,2,,, where t,,1,, is a parameter representing the G,,1,, duration of a ‘stem’ cell, and t,,2,, is the basic S+G,,2,,+M phases", sort out odd ,, and +
- [x] Formatting: in paragraph starting "Next we instantiate an instance of the PDE class...", remove lots of extra " in mathematical expressions
- [x] Formatting: in "the quantity of interest in the cells’ data is “oxygen”", add closing bracket
- [x] Broken link: "[wiki:UserTutorials/VisualizingWithParaview]"

[Running Vertex Based Crypt Simulations](https://chaste.github.io/docs/user-tutorials/runningvertexbasedcryptsimulations/)
- [x] Formatting: in "T. Nagai and H. Honda (“A dynamic cell model for the formation of epithelial tissues”, Philosophical Magazine Part B 81:699-719)", add a hyperlink to the DOI for this paper (https://doi.org/10.1080/13642810108205772)
- [x] Broken link: "UserTutorials/RunningMeshBasedCryptSimulations"

[Running Vertex Based Simulations](https://chaste.github.io/docs/user-tutorials/runningvertexbasedsimulations)
- [x] Formatting: in "T. Nagai and H. Honda (“A dynamic cell model for the formation of epithelial tissues”, Philosophical Magazine Part B 81:699-719)", add a hyperlink to the DOI for this paper (https://doi.org/10.1080/13642810108205772)

[Visualizing With Paraview](https://chaste.github.io/docs/user-tutorials/visualizingwithparaview)
- [x] Broken link: "UserTutorials/RunningNodeBasedSimulations"

Other queries/suggestions
- [ ] We refer to the java visualisers in some of these user tutorials; did we decide to drop these in favour of doing everything in Paraview? If not, I guess we should double check that the java visualisers still work as expected (and ideally test them in some way)?
- [ ] In these user tutorials, we refer to test output directories such as  `/tmp/$USER/testoutput/CellBasedDemo2/results_from_time_0` - is this where the test output would be if using Chaste Docker?
- [x] The very last code snippet before the Full code section in several of these tutorials is just "};", and could probably be merged into the previous code snippet before the last paragraph of text.
- [x] I couldn't see how to navigate to any user tutorials from the header menu.

**Comment by fcooper8472** [comment]
Maths mode is (nearly) working. https://github.com/Chaste/Chaste/commit/b462cf16fe41cf6392ef62fb50b251bcbc79aee2 updated one equation to maths mode:

```
 * two-dimensional cell population which lie outside the elliptical domain given in
 * Cartesian coordinates by the equation $\left(\frac{x}{20}\right)^2 + \left(\frac{y}{10}\right)^2 < 1$.
 * To implement this we define a new cell killer class, `MyCellKiller`,
```

And this is now rendered [like so](https://chaste.github.io/docs/user-tutorials/creatingandusinganewcellkiller/):
![image](https://github.com/Chaste/Chaste/assets/3770306/7aec15cf-4f6a-48dd-95ff-b7fab74a1479)

Somehow it's almost repeating the maths twice, once rendered and once partially rendered. I'll open an issue with the website theme creator and see what happens.

**Comment by fcooper8472** [comment]
I've found a workaround.

We can now render maths!

**Comment by mirams** [comment]
There are various places where we used two quote marks `''` around text, which used to make it italic, so those should probably all be changed to whatever does that now - asterixes?

**Comment by mirams** [comment]
There were actually pictures on some of them: https://chaste.cs.ox.ac.uk/trac/wiki/UserTutorials/SolvingLinearParabolicPdeSystemsWithCoupledOdeSystems which is just rendering nonsense now: 
<img width="1077" alt="image" src="https://github.com/Chaste/Chaste/assets/858776/8355053c-db2e-46ef-9051-ad41f214160c">

That worked because they were just wiki pages that could have files attached, and updating the text didn't affect the files.

(you could check for `[[` and `]]` in the website pages, as it probably indicates a trac macro that hasn't been translated!)

**Comment by fcooper8472** [comment]
I think for images we can just manually upload those to the website.

**Comment by mirams** [comment]
Note that we will want a nicer landing page (compare https://chaste.github.io/docs/user-tutorials/ and https://chaste.cs.ox.ac.uk/trac/wiki/UserTutorials) where does the landing page get made at the moment @fcooper8472 ?

**Comment by mirams** [comment]
The "3D" is missing from the title here: https://chaste.github.io/docs/user-tutorials/monodomain3dexample/
vs. https://chaste.cs.ox.ac.uk/trac/wiki/UserTutorials/Monodomain3dExample which seems like a @fcooper8472 task!

**Comment by mirams** [comment]
We also have a whole bunch of *manually* written tutorials here: https://chaste.cs.ox.ac.uk/trac/wiki/UserTutorials/CardiacExecutable which haven't made the transition.

**Comment by fcooper8472** [comment]
> Note that we will want a nicer landing page (compare https://chaste.github.io/docs/user-tutorials/ and https://chaste.cs.ox.ac.uk/trac/wiki/UserTutorials) where does the landing page get made at the moment @fcooper8472 ?

That's just this index page:
https://github.com/Chaste/Chaste.github.io/blob/main/site/content/docs/user-tutorials/_index.md

The links to each tutorial are auto-generated.

**Comment by fcooper8472** [comment]
> We also have a whole bunch of _manually_ written tutorials here: https://chaste.cs.ox.ac.uk/trac/wiki/UserTutorials/CardiacExecutable which haven't made the transition.

Oh dear.

I had no idea there were manually written tutorials! Are they just all mixed in with the auto-generated ones?

Can you maybe open a new issue with a list of all the manual ones?

**Comment by mirams** [comment]
They are all under that address above I think...

**Comment by mirams** [comment]
Added a pull request to see how these are looking #208

**Comment by mirams** [comment]
merged in that pull request so we can see how it looks now

**Comment by mirams** [comment]
Now I might be going mad @fcooper8472  @jmpf , but are any of these changes showing up? 

The action appears to have run: https://github.com/Chaste/Chaste/actions/runs/7628439041

But I can't see any changes, despite pressing refresh a lot. 

(e.g. [first commit above](https://github.com/Chaste/Chaste/commit/679ec25ee2e4844a880727e6f737b503df737959) removes `[[PageOutline]]` but it is still here: https://chaste.github.io/docs/user-tutorials/singlecellsimulation/ !)

**Comment by mirams** [comment]
Oh hold on, that github action just puts stuff in Chaste.github.io, and that had a github action that fell over: https://github.com/Chaste/Chaste.github.io/actions/runs/7628451072/job/20779547176

**Comment by mirams** [comment]
Now I don't *think* that's anything I did... although I was going to move and rename some images, but haven't done that yet I don't think, and didn't touch those images.

Saw some advice that they should end up in the `static` folder and some advice that they should be in `assets`, do we have a preference/policy?

**Comment by mirams** [comment]
OK, I now think it is something I did, in that I made some image macros work and now they need the images to be present!

**Comment by mirams** [comment]
Finally got my head up to speed with how to actually test this stuff:
 * Make changes to Chaste tutorials in Chaste source
 * `cd <Chaste src>`
 * `python python/infra/GenerateUserTutorials`
 * `cp tutorials/UserTutorials/* <Chaste.github.io src>/site/content/docs/user-tutorials`
 * `cd <Chaste.github.io src>/site`
 * `npm run dev`

**Comment by mirams** [comment]
Current status: my attempt at what a fix should look like is now over on the Chaste.github.io repo, but it isn't working so is just a draft pull request at the moment. Help welcome!
https://github.com/Chaste/Chaste.github.io/pull/26

**Comment by mirams** [comment]
I'm currently tidying up the maths on here: https://chaste.github.io/docs/user-tutorials/solvinglinearparabolicpdesystemswithcoupledodesystems/ just in case anyone else is doing anything

**Comment by mirams** [comment]
Pull request #211 to make latest progress live

**Comment by mirams** [comment]
Pleased with the equations on here: https://chaste.github.io/docs/user-tutorials/solvinglinearparabolicpdesystemswithcoupledodesystems/

**Comment by mirams** [comment]
A couple of cell-based tutorials make reference to java visualiser and https://chaste.cs.ox.ac.uk/trac/wiki/ChasteGuides/RunningCellBasedVisualization which is a page we haven't marked for migration, at the top of the that page it suggests to use paraview instead. Is there a different guide to visualizing cell based stuff in paraview to drop into the tutorials instead @AlexFletcher @fcooper8472 ?

**Comment by AlexFletcher** [comment]
Yes, this: [https://chaste.github.io/docs/user-tutorials/visualizingwithparaview](https://chaste.github.io/docs/user-tutorials/visualizingwithparaview)

**Comment by mirams** [comment]
Yeah, that isn't the friendliest guide if you haven't used Paraview before... 

Might be worth a quick check whether the java visualiser still works, as easiest way to look at things. Although guessing the docker might not be set up for it?? Any docker users want to see if that works @AlexFletcher @fcooper8472 ?

If we do strip out all the java visualiser stuff and just point to Paraview I think we'd want a nicer intro (screenshots with click this, or even a YouTube walkthrough). I would say even the Paraview state files for the tutorial outputs, but if we want to encourage people to know what they are doing in paraview those are cheating a bit. Obviously doesn't need to block release, but perhaps a new issue to improve the user guides/tutorials for that if we get rid of java visualiser mentions?

**Comment by mirams** [comment]
SO all that's left is getting the Chaste Executable tutorials (manual ones) ported over, and seeing if there's something wrong with the script as numbers seem to be missed out of page titles/names - e.g. Monodomain 3d Example is missing the "3d"

**Comment by MILeach** [comment]
## Required Before Release
- [x] Move the manually made UserTutorials/ChasteExecutable/* to new website (and manually add links to index page https://chaste.github.io/docs/user-tutorials/)
- [x] Investigate why titles don't have numbers like "3d" in them (https://chaste.github.io/docs/user-tutorials/monodomain3dexample/)
- [x] Alter the trac link at the top of https://chaste.github.io/docs/user-tutorials/ to point to where release versions of tutorials will end up.
- [ ] Add a new page/modify the existing one if it exists, specifying where test output goes in general & in docker
- [x] Add a link to new Immersed boundary tutorial to https://chaste.github.io/docs/user-tutorials/

## Nice to have
- [ ] Move java visualiser code to separate repo (code lives in the anim folder). Keep anim folder but replace code with a readme pointing to its new location
- [ ] Remove references to java visualiser from tutorials / docs
- [ ] Update paraview tutorial to make it a bit more user friendly

**Comment by mirams** [comment]
On the new website and looking good, moved remaining tasks to #224

**Comment by bdevans** [comment]
> * [ ]  In these user tutorials, we refer to test output directories such as  `/tmp/$USER/testoutput/CellBasedDemo2/results_from_time_0` - is this where the test output would be if using Chaste Docker?

See issue #224 for info.
