### ISSUE TITLE
Projects within projects

### ISSUE THREAD

**Issue by sanmitraghosh** [Chaste/Chaste#2]
Apparently its not possible to link to another user project from within a separate user project. The problem appears when trying to build using cmake. However, this isn't a issue while using scons.
I am facing this problem for my user project "ApPredict_GP" (https://github.com/sanmitraghosh/ApPredict_GP) which uses some of "ApPredict" (https://github.com/Chaste/ApPredict) code.

**Comment by fcooper8472** [comment]
This turns out to have been two separate problems:

1. CMake did not like projects without any source files.  Fixed in Chaste@0cbd80b99ed85619461088e6275074127852acae.

2. Projects were found via a call to `glob`, which would find the projects in a random order.  This meant that a dependent project may have been configured first, before CMake knew about the project on which it depended.  Fixed in Chaste@c21cd229944abb29b60e6e040e8cf0b01723e289

The CMake infrastructure should now work as expected.  Just make sure your project's CmakeLists.txt is set to find the Chaste components required, as well as the project on which it depends, appended by `project_` e.g.

```
find_package(Chaste COMPONENTS heart project_ApPredict)
```
Let me know if that works for you.
